name: AF_cache
channels:
  - conda-forge
  - bioconda
  - nvidia
dependencies:
  - python>=3.7,<3.11
  - aria2
  - openmm=8.0.0
  - pdbfixer=1.7
  - cudnn=8.9.7.29
  - kalign3=3.2.2
  - hhsuite=3.3.0
  - hmmer=3.3.2
  - cuda-nvcc
  - nextflow=24.10.4
