name: AF_cache
channels:
  - conda-forge
  - nvidia
  - bioconda
dependencies:
  - python>=3.7,<3.11
  - aria2
  - openmm=7.5.0
  - pdbfixer=1.7
  - cudnn=8.9.7.29
  - kalign3=3.2.2
  - hhsuite=3.3.0
  - hmmer=3.3.2
  - cuda-nvcc
  - pip
  - pip:
    - absl-py==1.0.0
    - biopython==1.79
    - chex==0.0.7
    - dm-haiku==0.0.12
    - dm-tree==0.1.8
    - docker==5.0.0
    - immutabledict==2.0.0
    - jax[cuda12]==0.4.26
    - ml-collections==0.1.0
    - numpy==1.24
    - pandas==2.0.3
    - scipy==1.11
    - tensorflow-cpu
    - flax==0.8.4
    - pytest<8.5.0
    - setuptools<72.0.0
